spring:
  application:
    name: tomopet
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-271f33ab-rtg20051117-a9c7.d.aivencloud.com:20787/tomopet?sslMode=REQUIRED
    username: avnadmin
    password: ${AIVEN_PASSWORD:your_password_here}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ksh051371@ync.ac.kr
    password: ${AIVEN_PASSWORD:your_password_here}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    org.springframework.web: debug

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXNlY3JldC1rZXktZm9yLXRvbW9wZXQtcHJvamVjdC1zZWNyZXQ=
  expiration-time: 3600000