spring:
  application:
    name: tomopet
  datasource:
    url: jdbc:mysql://reseau.proxy.rlwy.net:22300/railway
    username: root
    password: ZCYJRFsgHRngriYQegjWRDgmPtSbcwiJ
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true